### ISSUE TITLE
Artist Page

### ISSUE THREAD

**Issue by dandresfg** [zJaaal/js-player#25]
### To-Do

- [x] Artist info page
- [x] Most famous tracks
- [x] Most famous albums
- [x] Other related artists

# After that

- [x] Display the artist page and hide the others center containers
- [x] Home button has to hide the artist page

**Comment by zJaaal** [comment]
To-Dos has been completed please check Pull Request por Artist Page
